#################### CONFIGURATION FILE ####################
# This file contains the configuration for the audio data path,
# the embedding model, and the dimensionality reduction model.
#
# The embedding model must be a list either of one or multiple models.
# 
# The dimensionality reduction model must be just one of the supported models.


# PATHS:
# define paths for your audio data
audio_dir :       "bacpipe/evaluation/datasets/audio_test_files"

# CHOOSE FROM MODELS
models : [
    "animal2vec_xc",
    "animal2vec_mk",
    "audiomae",
    "aves",
    "biolingual",
    "birdaves",
    "birdnet",
    "avesecho_passt",
    "hbdet",
    "insect66",
    "mix2",
    "perch",
    "protoclr",
    "rcl_fs_bsed",
    "surfperch",
    "whaleperch",
    "vggish",
  ]


# embedding model name
embedding_model: ["audiomae"]

# dimensionality reduction model name.
supported_models: [
  "umap"
]
dim_reduction_model: "umap"
