## MAIN VARS ##
# audio_dir :       "/media/vincent/Extreme SSD/MA/20221019-Benoit/transfer_1780104_files_cfc5b86f/SABA01_201511_201604_SN275/resampled_2kHz/wav"

# fixed path, embeddings will be stored here, DO NOT CHANGE
embed_parent_dir :   "bacpipe/test_files/embeds"
umap_parent_dir :   "bacpipe/test_files/umap_embeds"


# supported formats of audio files
audio_suffixes: ['.wav', '.WAV', '.aif', '.mp3']

# specify your device ['cpu', 'cuda', ...]
device: 'cpu'

# UMAP settings
n_neighbors : 50
min_dist: 0.1
n_components : 2
metric : 'euclidean'
random_state: 42

